[book]
authors = ["anjin-byte"]
language = "en"
multilingual = false
src = "src"
title = "Training Agents for Panopticon"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.blocks]
command = "node node_modules/blocks-preprocessor/dist/blocks.js"

[output]

[output.html]
additional-css = [
    "node_modules/blocks-preprocessor/dist/mdbook-blocks/resources/bootstrap/scss/bootstrap.css",
    "node_modules/blocks-preprocessor/dist/mdbook-blocks/resources/blocks/scss/blocks.css",
]
additional-js = [
    "mermaid.min.js",
    "mermaid-init.js",
    "node_modules/blocks-preprocessor/dist/mdbook-blocks/resources/bootstrap/js/bootstrap.js",
]
